# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Article Content',
                'db_table': 'article_content',
                'managed': False,
                'verbose_name_plural': 'Article Contents',
            },
        ),
        migrations.CreateModel(
            name='ArticleDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_download_local_file_path', models.CharField(max_length=250, unique=True)),
                ('article_download_created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('article_download_last_updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('article_download_url', models.CharField(max_length=250, unique=True)),
                ('article_download_unique_id', models.CharField(max_length=250, unique=True)),
                ('article_download_is_parsed', models.SmallIntegerField(default=0, max_length=1)),
            ],
            options={
                'verbose_name': 'Article Download',
                'db_table': 'article_download',
                'managed': False,
                'verbose_name_plural': 'Article Downloads',
            },
        ),
        migrations.CreateModel(
            name='ArticleParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Article Parsed',
                'db_table': 'article_parsed',
                'managed': False,
                'verbose_name_plural': 'Article Parsed',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Author',
                'db_table': 'author',
                'managed': False,
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='ResolvedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_location_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Resolved Location',
                'db_table': 'resolved_location',
                'managed': False,
                'verbose_name_plural': 'Resolved Locations',
            },
        ),
        migrations.CreateModel(
            name='ResolvedLocationUnresolvedLocationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Resolved Location Unresolved Location Map',
                'db_table': 'resolved_location_unresolved_location_map',
                'managed': False,
                'verbose_name_plural': 'Resolved Location Unresolved Location Map',
            },
        ),
        migrations.CreateModel(
            name='ResolvedNewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_news_type_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Resolved News Type',
                'db_table': 'resolved_news_type',
                'managed': False,
                'verbose_name_plural': 'Resolved News Types',
            },
        ),
        migrations.CreateModel(
            name='ResolvedNewsTypeUnresolvedNewsTypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Resolved News Type Unresolved News Type Map',
                'db_table': 'resolved_news_type_unresolved_news_type_map',
                'managed': False,
                'verbose_name_plural': 'Resolved News Type Unresolved News Type Map',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Source',
                'db_table': 'source',
                'managed': False,
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='UnresolvedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unresolved_location_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Unresolved Location',
                'db_table': 'unresolved_location',
                'managed': False,
                'verbose_name_plural': 'Unresolved Locations',
            },
        ),
        migrations.CreateModel(
            name='UnresolvedNewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unresolved_news_type_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'UnResolved News Type',
                'db_table': 'unresolved_news_type',
                'managed': False,
                'verbose_name_plural': 'UnResolved News Types',
            },
        ),
    ]
